RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no 
# MAGIC_ENABLE = no

MUSIC_ENABLE = no
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes